import type { HookHandler } from "openclaw/hooks";
import { writeFile, mkdir } from "fs/promises";
import { join, dirname } from "path";

const FATHIPPO_API_URL = process.env.FATHIPPO_API_URL || "https://fathippo.ai/api/v1/simple/context";

interface FatHippoResponse {
  context?: string;
  memories?: Array<{ text: string; score?: number }>;
  error?: string;
}

const handler: HookHandler = async (event) => {
  // Only handle bootstrap events
  if (event.type !== "agent" || event.action !== "bootstrap") {
    return;
  }

  const apiKey = process.env.FATHIPPO_API_KEY;
  if (!apiKey) {
    console.log("[fathippo-recall] No FATHIPPO_API_KEY set, skipping");
    return;
  }

  const workspaceDir = event.context?.workspaceDir;
  if (!workspaceDir) {
    console.log("[fathippo-recall] No workspace directory, skipping");
    return;
  }

  try {
    // Extract context from bootstrap files or use session key as fallback
    const contextQuery = extractContextQuery(event);
    
    if (!contextQuery) {
      console.log("[fathippo-recall] No context to query, skipping");
      return;
    }

    console.log(`[fathippo-recall] Querying FatHippo for: "${contextQuery.slice(0, 50)}..."`);

    // Query FatHippo
    const response = await fetch(FATHIPPO_API_URL, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ message: contextQuery }),
    });

    if (!response.ok) {
      console.error(`[fathippo-recall] API error: ${response.status}`);
      return;
    }

    const data: FatHippoResponse = await response.json();
    
    // Format memories for context file
    const contextContent = formatContextFile(data, contextQuery);
    
    // Write to workspace
    const contextPath = join(workspaceDir, "FATHIPPO_CONTEXT.md");
    await mkdir(dirname(contextPath), { recursive: true });
    await writeFile(contextPath, contextContent, "utf-8");
    
    const memoryCount = data.memories?.length || 0;
    console.log(`[fathippo-recall] Wrote ${memoryCount} memories to ${contextPath}`);
    
  } catch (err) {
    console.error("[fathippo-recall] Error:", err instanceof Error ? err.message : String(err));
  }
};

function extractContextQuery(event: Parameters<HookHandler>[0]): string | null {
  // Try to get recent context from bootstrap files
  const bootstrapFiles = event.context?.bootstrapFiles;
  
  if (bootstrapFiles && bootstrapFiles.length > 0) {
    // Look for recent daily notes or memory files
    const memoryFile = bootstrapFiles.find(f => 
      f.path?.includes("memory/") || 
      f.path?.includes("MEMORY.md")
    );
    
    if (memoryFile?.content) {
      // Extract last few lines as query context
      const lines = memoryFile.content.split("\n").filter(l => l.trim());
      return lines.slice(-10).join(" ").slice(0, 500);
    }

    // Try SOUL.md or USER.md for identity context
    const identityFile = bootstrapFiles.find(f =>
      f.path?.includes("SOUL.md") || 
      f.path?.includes("USER.md")
    );

    if (identityFile?.content) {
      const lines = identityFile.content.split("\n").filter(l => l.trim());
      return lines.slice(0, 10).join(" ").slice(0, 500);
    }
  }
  
  // Fallback: use session key info
  if (event.sessionKey) {
    // Extract channel/group info from session key for context
    const parts = event.sessionKey.split(":");
    if (parts.length >= 3) {
      return `Recent context for ${parts.slice(2).join(" ")} session`;
    }
  }
  
  return "Recent working memory and context";
}

function formatContextFile(data: FatHippoResponse, query: string): string {
  const timestamp = new Date().toISOString();
  let content = `# FatHippo Context (Auto-Recalled)\n\n`;
  content += `> Query: "${query.slice(0, 100)}${query.length > 100 ? '...' : ''}"\n`;
  content += `> Retrieved: ${timestamp}\n\n`;
  
  if (data.context) {
    content += `## Relevant Context\n\n${data.context}\n\n`;
  }
  
  if (data.memories && data.memories.length > 0) {
    content += `## Retrieved Memories\n\n`;
    for (const memory of data.memories) {
      const score = memory.score ? ` (${(memory.score * 100).toFixed(0)}% match)` : '';
      content += `- ${memory.text}${score}\n`;
    }
    content += '\n';
  }
  
  if (!data.context && (!data.memories || data.memories.length === 0)) {
    content += `*No relevant memories found for this context.*\n`;
  }

  content += `---\n*Auto-generated by [@fathippo/openclaw-hook](https://fathippo.ai)*\n`;
  
  return content;
}

export default handler;
